spring:
 jpa:
  generate-ddl: true
 datasource:
  url: jdbc:postgresql://localhost:8432/app_db
  username: postgres
  password: postgres
  hikari:
   schema: app_schema
   connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
   connection-timeout: 10000

app:
 redis:
  enable: true
 cache:
  cacheType: redis
  cacheNames:
   - databaseBooks
   - databaseBooksByNameAndAuthor
   - databaseBooksById
   - databaseBooksByNameCategory
  caches:
   databaseBooks:
    expiry: 10m
   databaseBooksByNameAndAuthor:
    expiry: 10m
   databaseBooksById:
    expiry: 10m
   databaseBooksByNameCategory:
    expiry: 10m

server:
 port:8089